name = "Бабарыка Віктар"

[[bio]]
link = "https://babariko.by/o-viktore-babariko"
description = "Виктор Бабарико родился 9 ноября 1963 года в г. Минске. В 1988 году окончил механико-математический факультет Белорусского государственного университета. Трудовую деятельность начинал в НПО порошковой металлургии, откуда ушел в 1995 году с должности начальника отдела внешнеэкономических связей. В этом же году окончил Академию управления при Кабинете министров Беларуси, а пять лет спустя — магистратуру Белорусского государственного экономического университета. В банковской системе Беларуси работал с 1995 года. Председателем правления ОАО «Белгазпромбанка» стал в июле 2000 года. В 2008 году получил диплом Комиссии Республики Беларусь по делам ЮНЕСКО «за большой вклад в развитие интернациональных культурных связей». В 2014 году – почетное звание «Меценат культуры Беларуси». Лучший управляющий 2016 года и топ-менеджер 2018 года по версии банковской премии “Банк года”."

[[contacts]]
link = "https://babariko.vision"
description = "Афіцыйны сайт"

[[contacts]]
link = "https://www.youtube.com/channel/UCnMlkQPWeLjgiYcmayil6Bg"
description = "Афіцыйны youtube канал"

[[contacts]]
link = "https://www.instagram.com/viktar_babaryka"
description = "Instagram акаўнт"

[[contacts]]
link = "https://www.tiktok.com/@viktar_babaryka"
description = "TikTok акаўнт"

[[contacts]]
link = "https://t.me/viktarbabarykaofficial"
description = "Telegram канал"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=VbCcLOAI3Ss"
description = "Інтэрв'ю парталу tut.by"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=RTX4Bl_I2kA"
description = "Інтэрв'ю каналу \"Баренцева\""

[[video-interviews]]
link = "https://www.youtube.com/watch?v=A4T9vmiuWBo"
description = "Кандыdating"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=Q20HYaM90oU"
description = "Інтэрв'ю каналу \"MINSKI\""

[[video-interviews]]
link = "https://www.youtube.com/watch?v=MdrWeS08354"
description = "Інтэрв'ю Эхо Москвы"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=SwBFPU1tndY"
description = "Інтэрв'ю Deutsche Welle Russia"

[[text-interviews]]
link = "https://kyky.org/hero/vlast-gubit-nehvatka-lyubvi-posledniy-razgovor-s-viktorom-babariko-pered-zaderzhaniem"
description = "Інтэрв'ю \"KYKY.org\""
