name = "Бабарыка Віктар"

[[contacts]]
link = "https://babariko.by"
description = "Афіцыйны сайт"

[[contacts]]
link = "https://www.youtube.com/channel/UCnMlkQPWeLjgiYcmayil6Bg"
description = "Афіцыйны youtube канал"

[[contacts]]
link = "https://www.instagram.com/viktar_babaryka"
description = "Instagram акаўнт"

[[contacts]]
link = "https://www.tiktok.com/@viktar_babaryka"
description = "TikTok акаўнт"

[[interviews]]
link = "https://www.youtube.com/watch?v=VbCcLOAI3Ss"
description = "Інтэрв'ю парталу tut.by"

[[interviews]]
link = "https://www.youtube.com/watch?v=RTX4Bl_I2kA"
description = "Інтэрв'ю каналу \"Баренцева\""

[[interviews]]
link = "https://www.youtube.com/watch?v=A4T9vmiuWBo"
description = "Кандыdating"

[[interviews]]
link = "https://www.youtube.com/watch?v=Q20HYaM90oU"
description = "Інтэрв'ю каналу \"MINSKI\""

[[interviews]]
link = "https://www.youtube.com/watch?v=MdrWeS08354"
description = "Інтэрв'ю Эхо Москвы"

[[interviews]]
link = "https://www.youtube.com/watch?v=SwBFPU1tndY"
description = "Інтэрв'ю Deutsche Welle Russia"
