name = "Чэрачэнь Сяргей"
enabled = true

[[bio]]
link = "https://cherechen.by/biogphy"
description = "8 мая 1985 Родился в городе Кричев Могилёвской области. 2003-2008 Учился в Белорусском государственном университете информатики и радиоэлектроники на специальности «Многоканальные системы телекоммуникаций», параллельно - в Институте бизнес-технологий «Атлант-М». 2004-2005 Председатель молодёжного общественного объединения «Развитие». 2008-2017 Консультант по кризисному менеджменту. Разрабатывал и внедрял стратегии развития и проводил оценку/аудит состояния предприятия. 2016 Начал заниматься общественной деятельностью. 2017 Председатель Совета Белорусского республиканского общественного объединения «Дипломатия». 2018 Председатель партии «Грамада», которая активно участвует в политической жизни страны. 2018 по настоящее время Директор ООО «С58 Технолоджиз», компании, которая занимается инвестиционной и консалтинговой деятельностью."

[[contacts]]
link = "https://cherechen.by"
description = "Афіцыйны сайт"

[[contacts]]
link = "https://www.youtube.com/channel/UClerWNCM7snmB5RlhupvdUQ"
description = "Афіцыйны youtube канал"

[[contacts]]
link = "hhttps://www.instagram.com/svcherechen"
description = "Instagram акаўнт"

[[contacts]]
link = "https://www.tiktok.com/@svcherechen"
description = "TikTok акаўнт"

[[contacts]]
link = "https://t.me/vremya4e"
description = "Telegram канал"

[[contacts]]
link = "https://www.facebook.com/zache2020"
description = "Facebook акаўнт"

[[contacts]]
link = "https://vk.com/zache2020"
description = "Акаўнт у VK"

[[contacts]]
link = "https://ok.ru/group/57723949547647"
description = "Акаўнт у Аднакласніках"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=ABpDBp4EYao"
description = "Кандыdating"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=ggk49eD5JyY"
description = "Інтэрв'ю Realt.by"

`[[video-interviews]]
link = "https://www.youtube.com/watch?v=E2tbwMHOCM8"
description = "Пытаннечкі"
