name = "Чэрачэнь Сяргей"

[[bio]]
link = "https://cherechen.by/biogphy"
description = "8 мая 1985 Родился в городе Кричев Могилёвской области. 2003-2008 Учился в Белорусском государственном университете информатики и радиоэлектроники на специальности «Многоканальные системы телекоммуникаций», параллельно - в Институте бизнес-технологий «Атлант-М». 2004-2005 Председатель молодёжного общественного объединения «Развитие». 2008-2017 Консультант по кризисному менеджменту. Разрабатывал и внедрял стратегии развития и проводил оценку/аудит состояния предприятия. 2016 Начал заниматься общественной деятельностью. 2017 Председатель Совета Белорусского республиканского общественного объединения «Дипломатия». 2018 Председатель партии «Грамада», которая активно участвует в политической жизни страны. 2018 по настоящее время Директор ООО «С58 Технолоджиз», компании, которая занимается инвестиционной и консалтинговой деятельностью."

[[contacts]]
link = "https://cherechen.by"
description = "Афіцыйны сайт"

[[interviews]]
link = "https://www.youtube.com/watch?v=ABpDBp4EYao"
description = "Кандыdating"

[[interviews]]
link = "https://www.youtube.com/watch?v=ggk49eD5JyY"
description = "Інтэрв'ю Realt.by"

