name = "Чэрэчэнь Сяргей"

[[contacts]]
link = "https://cherechen.by"
description = "Афіцыйны сайт"

[[interviews]]
link = "https://www.youtube.com/watch?v=ABpDBp4EYao"
description = "Кандыdating"

[[interviews]]
link = "https://www.youtube.com/watch?v=ggk49eD5JyY"
description = "Інтэрв'ю Realt.by"

