name = "Дзмітрыеў Андрэй"
enabled = true

[[bio]]
link = "https://zapraudu.info/author/dmitriev"
description = "35 лет, живу в д.Волчковичи Дзержинского района, воспитываю трех сыновей. Окончил ЕГУ, бакалавр политических наук. Свободно владею английским языком. Основатель Школы молодых менеджеров государственного администрирования (SYMPA). Управлял собственным бизнесом. На президентских выборах 2010 и 2015 годов был начальником штабов Владимира Некляева и Татьяны Короткевич. Знаете за что мне болит? Что в Беларуси развивается лишь один город - Минск. Из провинции бегут в столицу, потому что только там есть хоть сколько удобства для жизни и возможность заработать. По-человечески я понимаю этих людей. В двухмиллионном городе сегодня за ту же самую работу, что в Узде, Ивье или Бешенковичах, платят на 30% больше, да и вообще – в принципе есть работа! А в регионах люди даже дают взятки, чтобы попасть хоть на какое место за 3 миллиона! Не может развитие страны держаться на одном городе, как на одном гвозде. Уверенный рост должен быть основан на развитии регионов. Чтобы в малых и средних городах хотелось жить, было где работать, образование в школах и медицина не многим уступали столице. Я специально ездил в Польшу, Финляндию, Швецию, чтобы изучить их опыт. Разговаривал с простыми людьми, чиновниками, политиками. Беларусы при своей работоспособности и уважению к порядку могут всего этого достичь, но нужно добиться, чтобы государство обратило внимание на малые и средние города и начало целенаправленно создавать в них условия и для жизни, и для работы. Через развитие частной инициативы, создание локальных производств, выделение земли и помощи в постройке домов, привлечение специалистов, обеспечение условий для досуга, полноценного воспитания детей. Все это сократит катастрофический разрыв с Минском и обеспечит достойную жизнь тем, кто живет вне столицы, а Беларуси – экономический рост и развитие."

[[contacts]]
link = "http://dzmitryeu.by"
description = "Афіцыйны сайт"

[[contacts]]
link = "https://www.facebook.com/DmitrievAndrei"
description = "Facebook акаўнт"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=4Aq61BC0qNM"
description = "Інтэрв'ю Realt.by"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=Pr1UEut5F1k"
description = "Інтэрв'ю Белсат"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=-cgTzYe1CCw"
description = "Кандыdating"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=hCU7jxbaB1M"
description = "Пытаннечкі"

[[text-interviews]]
link = "https://www.mk.ru/politics/2020/06/17/kandidat-v-prezidenty-belorussii-rasskazal-o-repressiyakh-i-proslushke.html"
description = "Інтэрв'ю \"MK.ru\""
