name_ru = "Дмитриев Андрей"
name_by = "Дзмітрыеў Андрэй"

[[interviews]]
link = "https://www.youtube.com/watch?v=-cgTzYe1CCw"
description_ru = "Кандыdating"
description_by = "Кандыdating"

[[contacts]]
link = "https://www.facebook.com/DmitrievAndrei/"
description_ru = "Facebook аккаунт"
description_by = "Facebook акаунт"
