name = "Дзмітрыеў Андрэй"

[[interviews]]
link = "https://www.youtube.com/watch?v=-cgTzYe1CCw"
description = "Кандыdating"

[[contacts]]
link = "https://www.facebook.com/DmitrievAndrei/"
description = "Facebook акаўнт"

[[interviews]]
link = "https://www.youtube.com/watch?v=4Aq61BC0qNM"
description = "Інтэрв'ю Realt.by"

[[interviews]]
link = "https://www.youtube.com/watch?v=Pr1UEut5F1k"
description = "Інтэрв'ю Белсат"


#https://www.mk.ru/politics/2020/06/17/kandidat-v-prezidenty-belorussii-rasskazal-o-repressiyakh-i-proslushke.html?fbclid=IwAR3xIaX_uXT9hC1uO-nTPNaXzT0Sxsv678kA0QijDwPhOd6Twz65iKc5D1w