name = "Дзмітрыеў Андрэй"

[[interviews]]
link = "https://www.youtube.com/watch?v=-cgTzYe1CCw"
description = "Кандыdating"

[[contacts]]
link = "https://www.facebook.com/DmitrievAndrei/"
description = "Facebook акаунт"
