name_ru = "Канопацкая Анна"
name_by = "Канапацкая Ганна"

[[interviews]]
link = "https://www.youtube.com/watch?v=R9qz5iga6hw"
description_ru = "Кандыdating"
description_by = "Кандыdating"

[[contacts]]
link = "https://www.facebook.com/anna.kanopatskaya/"
description_ru = "Facebook аккаунт"
description_by = "Facebook акаунт"
