name = "Канапацкая Ганна"

[[interviews]]
link = "https://www.youtube.com/watch?v=R9qz5iga6hw"
description = "Кандыdating"

[[contacts]]
link = "https://www.facebook.com/anna.kanopatskaya/"
description = "Facebook акаунт"
