name = "Канапацкая Ганна"

[[interviews]]
link = "https://www.youtube.com/watch?v=R9qz5iga6hw"
description = "Кандыdating"

[[interviews]]
link = "https://www.youtube.com/watch?v=HnUsvc6G1WA"
description = "Інтэрв'ю Белсат"

[[interviews]]
link = "https://www.youtube.com/watch?v=gtb0Ca1XqyA"
description = "Інтэрв'ю Realt.by"

[[contacts]]
link = "https://www.facebook.com/anna.kanopatskaya/"
description = "Facebook акаўнт"

[[contacts]]
link = "https://instagram.com/anna.kanopatskaya"
description = "Instagram акаўнт"
