name = "Цапкала Валерый"

[[contacts]]
link = "https://tsepkalo.by"
description = "Афіцыйны сайт"

[[contacts]]
link = "https://www.youtube.com/channel/UCyNQ-QygZYwUgXSUQwFtzmQ/"
description = "Афіцыйны youtube канал"

[[contacts]]
link = "https://www.instagram.com/tsepkalo.official"
description = "Instagram акаунт"

[[interviews]]
link = "https://www.youtube.com/watch?v=hi4Xl7XHfYI"
description = "Інтэрв'ю парталу tut.by"

[[interviews]]
link = "https://www.youtube.com/watch?v=X9hUOCJJzwo"
description = "Інтэрв'ю каналу \"Баренцева\""

[[interviews]]
link = "https://www.youtube.com/watch?v=F9PF7dMXX9w"
description = "Кандыdating"

[[interviews]]
link = "https://www.youtube.com/watch?v=KwlOUe28ztM"
description = "Інтэрв'ю Эхо Москвы"

[[interviews]]
link = "https://www.youtube.com/watch?v=FveI_1gwAvE"
description = "Інтэрв'ю каналу \"MINSKI\""
