name = "Цапкала Валерый"

[[bio]]
link = "https://tsepkalo.by"
description = "Валерий Вильямович Цепкало родился 22 февраля 1965 г. в городе Гродно, в семье инженеров-химиков. Окончил среднюю школу № 14 г. Гродно. В 1982-1984 гг. учился в Белорусском технологическом институте в Минске. С 1984 по 1986 гг. проходил воинскую службу в Ракетных войсках стратегического назначения. В 1986 г. поступил в Московский государственный институт международных отношений МИД СССР, который окончил с отличием. Закончил аспирантуру, получил ученую степень кандидата юридических наук. Карьерный путь дипломата начал в 1991 г. сотрудником посольства СССР в Финляндии. После распада Советского Союза вернулся в Минск, где в 1992 г. занял дипломатическую должность в Министерстве иностранных дел Республики Беларусь. В 1993-1994 гг. был советником Председателя Верховного совета Республики Беларусь по внешнеполитическим и внешнеэкономическим вопросам. Позднее стал советником Исполнительного секретаря СНГ. В 1994 г. стал первым заместителем министра иностранных дел Республики Беларусь. С 1997 по 2002 гг. был Чрезвычайным и Полномочным Послом Республики Беларусь в Соединенных Штатах Америки и в Мексике. В 2004 г. выступил инициатором создания Парка высоких технологий. С 2005 по 2017 гг. был директором Парка высоких технологий в Республике Беларусь. С 2017 г. является основателем ИТ-стартапа «Всемирная биографическая энциклопедия», который стал самым полным в мире источником информации о людях. С 2017 г. выступал международным консультантом правительств Узбекистана, Азербайджана, Грузии и Саудовской Аравии по созданию технологических парков."

[[bio]]
link = "https://ru.wikipedia.org/wiki/Цепкало,_Валерий_Вильямович"
description = "Вікіпедыя"

[[contacts]]
link = "https://tsepkalo.by"
description = "Афіцыйны сайт"

[[contacts]]
link = "https://www.youtube.com/channel/UCyNQ-QygZYwUgXSUQwFtzmQ/"
description = "Афіцыйны youtube канал"

[[contacts]]
link = "https://www.instagram.com/tsepkalo.official"
description = "Instagram акаўнт"

[[contacts]]
link = "https://t.me/tsepkalo2020"
description = "Telegram канал"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=hi4Xl7XHfYI"
description = "Інтэрв'ю парталу tut.by"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=X9hUOCJJzwo"
description = "Інтэрв'ю каналу \"Баренцева\""

[[video-interviews]]
link = "https://www.youtube.com/watch?v=F9PF7dMXX9w"
description = "Кандыdating"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=KwlOUe28ztM"
description = "Інтэрв'ю Эхо Москвы"

[[video-interviews]]
link = "https://www.youtube.com/watch?v=FveI_1gwAvE"
description = "Інтэрв'ю каналу \"MINSKI\""

[[video-interviews]]
link = "https://www.youtube.com/watch?v=GgVzIu9G76s"
description = "Інтэрв'ю Realt.by"

[[text-interviews]]
link = "https://www.golos-ameriki.ru/a/belarus-elections-tsepkalo-interview/5468170.html"
description = "Інтэрв'ю \"Голос Америки\""

[[text-interviews]]
link = "https://www.rbc.ru/politics/22/06/2020/5ef076289a79478bbd423572"
description = "Інтэрв'ю \"РБК\""

[[text-interviews]]
link = "https://ria.ru/20200623/1573317066.html"
description = "Інтэрв'ю \"РИА Новости\""

[[text-interviews]]
link = "https://vz.ru/news/2020/6/23/1046518.html"
description = "Інтэрв'ю \"Деловая газета Взгляд\""

[[text-interviews]]
link = "https://www.forbes.ru/obshchestvo/403817-hochu-prevratit-vsyu-stranu-v-park-vysokih-tehnologiy-intervyu-s-poslednim"
description = "Інтэрв'ю Forbes"
